name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Deploy on Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
